spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      maximum-pool-size: 30
      max-lifetime: 60000
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 5000
      pool-name: Spring-HikariPool

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

  messages:
    basename: errors

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  data:
    redis:
      host: localhost
      port: 6379

lock:
  datasource:
    hikari:
      maximum-pool-size: 20
      max-lifetime: 60000
      jdbc-url: ${JDBC_URL}
      username: ${JDBC_USERNAME}
      password: ${JDBC_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 5000
      pool-name: Lock-HikariPool

logging:
  level:
    org.hibernate.SQL: debug